# Generated by Django 5.0.7 on 2024-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
