# Generated by Django 5.0.7 on 2024-09-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_register_city_alter_register_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.FileField(max_length=52, upload_to='media'),
        ),
    ]
