# Generated by Django 5.0.7 on 2024-10-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_register_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(default='hi', max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(default='hi', max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(default='hi', max_length=52),
        ),
    ]
