# Generated by Django 5.0.7 on 2024-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_alter_register_city_alter_register_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=52),
        ),
    ]
