# Generated by Django 5.0.7 on 2024-10-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_alter_register_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hobbies',
            field=models.JSONField(default='shg', max_length=52),
        ),
    ]
