# Generated by Django 5.0.7 on 2024-10-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_alter_register_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='hobbies',
        ),
    ]
