# Generated by Django 5.0.7 on 2024-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0010_remove_register_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='hobbies',
            field=models.JSONField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.FileField(max_length=52, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
