# Generated by Django 5.0.7 on 2024-10-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_register_hobbies_alter_register_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='hobbies',
            field=models.JSONField(default='hi', max_length=52),
        ),
    ]
