# Generated by Django 5.0.7 on 2024-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0013_alter_register_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.FileField(default='hh', max_length=52, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(default='hh', max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(default='hh', max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='hobbies',
            field=models.JSONField(default='hh', max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(default='hh', max_length=52),
        ),
    ]
