# Generated by Django 5.0.7 on 2024-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_alter_register_avatar_alter_register_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.FileField(max_length=52, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='hobbies',
            field=models.JSONField(max_length=52),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=52),
        ),
    ]
