# Generated by Django 5.0.7 on 2024-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0015_alter_register_avatar_alter_register_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=52)),
                ('password', models.CharField(max_length=52)),
            ],
        ),
    ]
