# Generated by Django 5.0.7 on 2024-10-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='passwords', serialize=False, to='myapp1.register'),
        ),
    ]
