# Generated by Django 5.0.7 on 2024-10-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0017_alter_password_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.register'),
        ),
        migrations.AlterField(
            model_name='password',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
