# Generated by Django 5.0.7 on 2024-10-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0018_password_ids_alter_password_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='ids',
        ),
    ]
