# Generated by Django 5.0.7 on 2024-10-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0019_remove_password_ids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Password',
            new_name='Login',
        ),
    ]
