# Generated by Django 5.0.7 on 2024-10-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0021_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='nil', max_length=52),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='nil', max_length=52),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='nil', max_length=52),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='nil', max_length=52),
        ),
    ]
