# Generated by Django 5.0.7 on 2024-10-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0022_contact_email_contact_message_contact_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=52)),
                ('category', models.CharField(max_length=52)),
                ('duration', models.CharField(max_length=52)),
                ('fee', models.CharField(max_length=52)),
            ],
        ),
    ]
