# Generated by Django 5.0.7 on 2024-10-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0023_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
