# Generated by Django 5.0.7 on 2024-10-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0024_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='coursesselected',
            field=models.CharField(max_length=585, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.ImageField(max_length=52, upload_to='files/'),
        ),
    ]
