# Generated by Django 5.0.7 on 2024-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0025_login_coursesselected_alter_register_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=152, null=True),
        ),
    ]
