# Generated by Django 5.0.7 on 2024-10-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0026_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.ImageField(default='files/m_aKT2e2q.jpg', max_length=52, upload_to='files/'),
        ),
    ]
