# Generated by Django 5.0.7 on 2024-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0028_alter_register_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=52)),
                ('duration', models.CharField(max_length=52)),
                ('fee', models.CharField(max_length=52)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='avatar',
            field=models.ImageField(default='files/hs_aXjcotW.png', max_length=502, upload_to='files/'),
        ),
    ]
